### PR TITLE
WIP: Add ability to send review ban stats to the summary spreadsheet

### PR DESCRIPTION
**Pull request by Oaphi**
This PR adds support for sending review ban stats to the summary spreadsheet via the userscript.

For the update to work, the production version has to create a Google Cloud Project and set 3 variables (required by Google):

```typescript
const sheetsApiKey = ""; // API key created on https://console.cloud.google.com/apis/credentials
const appClientId = ""; // OAuth 2.0 Client IDs created on https://console.cloud.google.com/apis/credentials
const statsSpreadId = ""; // spreadsheet id, i.e. 1GIH-6CH58lJbQ18vPcsrBVzlHwjOmuYTxktMbLV9TWk
```

A potential caveat is that the `https://www.googleapis.com/auth/spreadsheets` (read/write) scope requested from the user can be quite scary for security-conscious users, but there is no other way around for allowing writes to a spreadsheet on behalf of a user (no, unfortunately, the scope cannot be "scoped"). That said, the authorization is incremental (i.e. does not happen until the user actually tries to perform the action), so should not disrupt the normal flow of the userscript.

### CODE REVIEW

**Comment by Oaphi** [comment]
Regarding the fc65bb3 , for now, the simplest option is to prompt the user for all three variables (API key, spreadsheet id, and client id). Possible areas of improvement: add a "do not ask me anymore" button and account for local storage being inaccessible as well (rare case, but not impossible).

**Comment by samliew** [comment]
Ok with adding this. Need me to do anything else?

**Comment by Oaphi** [comment]
@samliew thank you for taking a look! No, nothing for now, it is still a WIP, I would like to make some polishing changes before considering it to be in good enough shape - in particular, I feel a bit iffy about resorting to prompts for setting the Sheets API-related properties to storage

**Comment by samliew** [comment]
I also have another rudimentary userscript that has a simple interface to modify settings that saves to localstorage, and exposes functions to read from. Check out SOMU-options

**Comment by Oaphi** [comment]
@samliew  oh, that's exactly what I have been thinking of. I guess the only thing I'd do is integrate it with the userscript manager-agnostic storage of mine as it would make it more flexible in terms of storing/loading info. Gladly, the API of it modeled after the `Storage` API (albeit with a small caveat of being a Promise-based API due to Greasemonkey)

**Comment by Oaphi** [comment]
Integrated SOMU-options to the userscript *and* allowed users who do not want to use the script to use the prompts.
Also made a tweak to the SOMU-options userscript to allow for overriding `store` value with compatible storage objects.

Still needs a tweak to be able to work with promise-based APIs (e.g. Greasemonkey's storage), but it means either a breaking change or devising a way for switching between promise-based and synchronous API.

**Review by samliew — APPROVED** [review]

**Comment by makyen** [comment]
@Oaphi The normal way to handle needing to be compatible with both synchronous and asynchronous APIs is to treat all of them as asynchronous. The Synchronous APIs just immediately return, or just block your code as the async call is being set up. If the async APIs are Promise based, then the normal thing to do is make all of them Promise based by adding Promise wrappers to all the non-Promise based APIs.

If you're just interested specifically in the Userscript APIs, then you should look at [the gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill) which will add a Promise wrapper to the Userscript APIs which are provided by userscript managers other than Greasemonkey (or, at least, most of the APIs where there's overlap).

**Comment by Oaphi** [comment]
@makyen I know, and a switch to "always async" would be my normal mode of operation in this case too. However, in this particular case making the API of SOMU-options promise-based is a breaking change for scripts that rely on it. Of course, it is plausible to just update all the other scripts and be done with it, but I am not sure the benefits outweigh the risk of potentially breaking scripts (even if for a short time) that are actively used for moderation purposes.

My current idea is to check whether the [value returned](https://github.com/samliew/SO-mod-userscripts/blob/master/SOMU-options.user.js#L43) from the storage is a `Promise` and switch out the rest of the method with a promise-based implementation. This way userscripts that expect the storage to have synchronous API will continue to function with zero changes.

**Pull request merged**
