### PR TITLE
Bump pagesize

### PR DESCRIPTION
**Pull request by LunarWatcher**
https://meta.stackoverflow.com/questions/419687/i-received-a-message-we-are-no-longer-receiving-questions-from-this-account

**Type of change**
- [X] Bugfix
- [ ] New feature

**Pre-review checklist**
- [x] I have commented my code
- [x] I have bumped the minor version of the changed userscript(s)

**Brief description of the change:**

- Bumps the pagesize from 30 to 50. A [recent meta post](https://meta.stackoverflow.com/questions/419687/i-received-a-message-we-are-no-longer-receiving-questions-from-this-account) broke the 30 question mark

### CODE REVIEW

**Comment by samliew** [comment]
This also sets the user's default pagesize to 50, so I am not very keen on doing this.

**Comment by LunarWatcher** [comment]
Hmm, what other options are there then? Guessing the next alternative is diving into the API, and that feels overkill

**Comment by makyen** [comment]
@LunarWatcher You're looking for deleted content. The only places you'll be able to see deleted content is in the user's profile or in search results. Deleted content is definitely not available from the SE API.

You could continue to use search results, but fetch multiple pages.

**Comment by makyen** [comment]
@samliew I agree that it's very annoying to have the script change the user's default search `pagesize`, but *you're already doing that* by specifying `&pagesize=30`. Once I tracked down what had changed my default page size from 50 to 30, removing the `&pagesize=30` was one of the first things I changed in my copy of this script.

The right solution to this is to remove the `&pagesize=30` and either:
1. Live with the number of results which are returned with a single page using the user's currently defined `pagesize`. You can return the total number and links for the results retrieved and just indicate that there are more, perhaps with a note to the moderator that they can get more if they set their `pagesize` larger. OR
2. Fetch more/all pages: If the reported number of results is higher than the number or results returned in the page, then fetch another page. Repeat until you have all the results. It's a bit more complicated, but it's the right way to do it. Obviously, there should be limits on the number of pages fetched (i.e. if something goes wrong, you don't want to fetch 100 pages), and you'll have to limit the rate at which you fetch them in order to not trigger SE's rate limiting.

**Comment by LunarWatcher** [comment]
I'm not too keen on proper scraping of several pages. SE's rate limits are harsh, and I'd like to avoid them

**Comment by LunarWatcher** [comment]
Looks like the internal consensus is to reduce these comments altogether, so I'll go ahead and close this

**Pull request closed without merging**
